---
language: go
go:
  - 1.15.x
services:
  - docker
install:
  - |
    # Install ko
    curl -fsL https://github.com/google/ko/releases/download/v0.8.1/ko_0.8.1_Linux_x86_64.tar.gz | sudo tar xzf - -C /usr/local/bin ko

deploy:
  - provider: script
    script: make release TAG=latest
    on:
      branch: master
  - provider: script
    script: make release TAG=$TRAVIS_TAG
    on:
      tags: true
      all_branches: true
