kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shipwright-build-controller
subjects:
- kind: ServiceAccount
  name: shipwright-build-controller
  namespace: shipwright-build
roleRef:
  kind: ClusterRole
  name: shipwright-build-controller
  apiGroup: rbac.authorization.k8s.io
