name: Nightly Release

on:
  push:
    branches: ['sign-release-images']
  workflow_dispatch:  # Manual trigger

jobs:
  nightly:
    permissions:
      id-token: write  # To be able to get OIDC ID token to sign images.
      contents: read
      packages: write

    # if: ${{ github.repository == 'shipwright-io/build' }} TODO remove
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%s')"

    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    # Install tools
    - uses: imjasonh/setup-crane@01d26682810dcd47bfc8eb1efe791558123a9373
    - uses: imjasonh/setup-ko@20b7695b536c640edfafdd378d96c760460f29d6
    - uses: sigstore/cosign-installer@v1.2.0

    - name: Generate and upload release YAMLs
      env:
        TAG: "nightly-${{ steps.date.outputs.date }}"
        IMAGE_HOST: ghcr.io
        IMAGE_NAMESPACE: ${{ github.repository_owner}}/${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make release

        mv release.yaml nightly-${{ steps.date.outputs.date }}.yaml
        #gh release upload nightly nightly-${{ steps.date.outputs.date }}.yaml

        mv release-debug.yaml nightly-${{ steps.date.outputs.date }}-debug.yaml
        #gh release upload nightly nightly-${{ steps.date.outputs.date }}-debug.yaml

        mv sample-strategies.yaml nightly-${{ steps.date.outputs.date }}-sample-strategies.yaml
        #gh release upload nightly nightly-${{ steps.date.outputs.date }}-sample-strategies.yaml

    - name: Sign released images
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        for f in \
          nightly-${{ steps.date.outputs.date }}.yaml \
          nightly-${{ steps.date.outputs.date }}-debug.yaml; do
          grep -o "ghcr.io[^\"]*" $f | xargs cosign sign -a sha=${{ github.sha }} -a run=${{ github.run_id }}
        done
